# The URL this site will be built for
base_url = "https://hanson-hschang.github.io/persona-zola-theme"

# The basic site information
title = "Persona - Zola Theme "
author = "Persona, Zola Theme"
description = "A portfolio, a resume, a blog, and a Zola theme."

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

taxonomies = [
  { name = "tags", feed = true },
  { name = "categories", feed = true },
]

[markdown]
# Whether to do syntax highlighting
# Theme can be customized by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

# Whether external links are to be opened in a new tab
# If this is true, a `rel="noopener"` will always automatically be added for security reasons
external_links_target_blank = true

# Whether to set rel="nofollow" for all external links
external_links_no_follow = false

# Whether to set rel="noreferrer" for all external links
external_links_no_referrer = true

[extra]

[extra.persona]
# Note: landing page title and subtitles are configured in content/_index.md

# Social links
# A list of your social media profiles to display.
#
# Find icon classes from:
# - Bootstrap Icons: https://icons.getbootstrap.com/
# - Academicons: https://jpswalsh.github.io/academicons/
social_links = [
  { name = "GitHub", url = "https://github.com/hanson-hschang/persona-zola-theme", icon_class = "bi bi-github" },
]

# Contact information
# A list of contact information to display.
#
# Find icon classes from:
# - Bootstrap Icons: https://icons.getbootstrap.com/
contact_infos = [
  { item = "Name", content = "Persona, Zola Theme", icon_class = "bi bi-person"},
  { item = "Email", content = "hanson.hschang+persona.zola.theme@gmail.com", icon_class = "bi bi-envelope"}
]
# To set up web3form contact form, please create your public access key (following the instruction at https://web3forms.com/).
# To remove the contact form, please comment out the following line.
web3form_public_key = "YOUR-ACCESS-KEY-HERE"

# Footer
quote = "There's the private persona and the public persona, and the two shall never meet. --- Liev Schreiber"
copyright = "&copy; All Rights Reserved"
credits = "Powered by [Zola](https://www.getzola.org/), [Bootstrap](https://getbootstrap.com/), and [Web3Forms](https://web3forms.com/)"
