# The URL the site will be built for
base_url = "https://hanson-hschang.github.io/zola-persona-theme"

# The site title and description
title = "Persona Theme - Zola"
description = "A portfolio, a resume, a blog, and a Zola theme."
author = "Zola, Persona Theme"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

taxonomies = [
  { name = "tags" },
  { name = "categories" },
]

[markdown]
# Whether to do syntax highlighting
# Theme can be customized by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

# Whether external links are to be opened in a new tab
# If this is true, a `rel="noopener"` will always automatically be added for security reasons
external_links_target_blank = true

# Whether to set rel="nofollow" for all external links
external_links_no_follow = false

# Whether to set rel="noreferrer" for all external links
external_links_no_referrer = true

# Variables that can be overridden in the end user's `config.toml`
[extra]
server_side_katex = true # true: enable server-side KaTeX rendering via scripts/katex.js (this will also include KaTeX CSS and fonts in the build)
quote = "There's the private persona and the public persona, and the two shall never meet. --- Liev Schreiber"
social_links = [
  { name = "GitHub", url = "https://github.com/hanson-hschang/zola-persona-theme", icon_class = "bi bi-github" },
]
copyright = "&copy; All Rights Reserved"
credits = "Powered by [Bootstrap](https://getbootstrap.com/), [Zola](https://www.getzola.org/), and [Web3Forms](https://web3forms.com/)"

[extra.contact]
infos = [
  { item = "Name", content = "Zola, Persona Theme", icon_class = "bi bi-person"},
  { item = "Email", content = "hanson.hschang+zola.persona.theme@gmail.com", icon_class = "bi bi-envelope"}
]
# To set up web3form contact form, please create your public access key (following the instruction at https://web3forms.com/),
# and uncomment the following line with the access key
# web3form_public_key = "YOUR_ACCESS_KEY_HERE"
